-- Add is_historical flag to calendar_shifts to distinguish imported historical data from engine-generated shifts
ALTER TABLE public.calendar_shifts
ADD COLUMN IF NOT EXISTS is_historical boolean DEFAULT false;

COMMENT ON COLUMN public.calendar_shifts.is_historical IS
  'true = imported from historical data (real manager schedules), false = generated by engine or manual';
