// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://covgwdbnyqdcygedcijl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdmd3ZGJueXFkY3lnZWRjaWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODk5Njk2MzAsImV4cCI6MTcwNTUyMTYzMH0.g_Ln8r0FHhyplQOj1CrmNMlHrpLdUPWfuLg-UTp5Cic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});